development:
  adapter: postgresql
  encoding: unicode
  database: cms_development
  pool: 5
  username: 
  password: 

staging:
  adapter: postgresql
  encoding: unicode
  database: cms_staging
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: cms_production
  pool: 5
  username: 
  password: 